apiVersion: v1
kind: ServiceAccount
metadata:
  name: network-checker
  namespace: kube-system
  labels:
    app: network-checker
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: network-checker
  labels:
    app: network-checker
rules:
- apiGroups: [""]
  resources: ["namespaces", "services"]
  verbs: ["get","list","delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: network-checker
  labels:
    app: network-checker
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: network-checker
subjects:
- kind: ServiceAccount
  name: network-checker
  namespace: kube-system
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: network-check
  namespace: kube-system
  labels:
    app: network-checker
spec:
  selector:
    matchLabels:
      app: network-checker
  template:
    metadata:
      labels:
        app: network-checker
    spec:
      serviceAccount: network-checker
      containers:
      - name: network-checker
        image: etiennetremel/k8s-network-checker
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 50m
            memory: 200Mi
